### PR TITLE
Pr/export use deep compare memoize

### PR DESCRIPTION
**Pull request by cvolant**
**What**:
Export useDeepCompareMemoize in src/index

**Why**:
This function can be useful in other circumstances. I have this need, and since it is not exported, for now I must duplicate the code.

**Checklist**:
- [ ] Documentation N/A
- [ ] Tests N/A
- [X] Ready to be merged

** Note **
I wondered if some docs are needed about this newly exported function. Since the existent secondary export, useDeepCompareEffectNoCheck, does not have documentation, I assumed it is not needed.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Sure. But yeah, let's leave it undocumented. Use at your own risk.

**Comment by kentcdodds** [comment]
@All-contributors please add @cvolant for code

**Comment by edzis** [comment]
@kentcdodds I am reaching for the same thing to deal with a large and frequently updating non-immutable redux state, but in my TS codebase it does not feel right to use something not exposed or covered by the types.
Would you re-consider exposing this?
Or what are the concerns you have about exposing that? Maybe I should be wary of that as well.

**Comment by kentcdodds** [comment]
Looks I said, use at your own risk. You could just copy/paste it. This library is really small.

**Pull request merged**
